### PR TITLE
Added PHP 5.5 and FEDORA_VERSION 3.8.1 to .travis.yml; removed obsole…

### PR DESCRIPTION
**Pull request by mjordan**
As discussed at https://github.com/discoverygarden/islandora_rest/pull/16#issuecomment-247863247.

### CODE REVIEW

**Comment by mjordan** [comment]
Tests under PHP 5.5 are failing with this:

```
Test DrupalWebTestCase->curlExec() failed: curl_setopt_array(): The  [error]
usage of the @filename API for file uploading is deprecated. Please
use the CURLFile class instead in
/home/travis/drupal-7.50/modules/simpletest/drupal_web_test_case.php
on line 1814
```

**Comment by mjordan** [comment]
Good news everyone! Tests now pass on PHP 5.5. But, tests on PHP < 5.5 now fail with this:

```
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Class 'CURLFile' not found in
/home/travis/build/discoverygarden/islandora_rest/tests/islandora_rest.test,
line 541
```

http://php.net/manual/en/class.curlfile.php says that CURLFile is available in "PHP 5 >= 5.5.0, PHP 7" so I'm not sure why the failures are happening. I can add logic to `islandora_rest.test` to check for PHP versions but before I do, am I missing something obvious?

**Comment by qadan** [comment]
That's a bit of a pickle ... it's a good catch though. If we set `CURLOPT_SAFE_UPLOAD` to `TRUE` in the [POST `curlExec()`](https://github.com/discoverygarden/islandora_rest/blob/aacb93eaf0e0a586b84bc95dfffebcb64d2af2a6/tests/islandora_http_rest_test_case.inc#L110-L116) does that make it work in both? Or ... actually it'll probably break it in >= 5.5, I dunno. They're [setting it by default in Drupal 8](https://www.drupal.org/node/2538260), but Drupal 8 also hard requires PHP 5.5.

I think if `CURLOPT_SAFE_UPLOAD` doesn't do the trick, then unfortunately, it'll have to be version-dependent.

**Comment by mjordan** [comment]
Will try setting `CURLOPT_SAFE_UPLOAD` to `TRUE` this evening, if it doesn't work, will add `PHP_VERSION` logic.

**Comment by qadan** [comment]
I'd also recommend jammin' that logic - if it winds up being necessary - in `IslandoraHttpRestTestCase::httpPost()` ... something like, 

``` php
if (PHP_MAJOR_VERSION >= 5 && PHP_MINOR_VERSION >= 5 && isset($data['file'])) { 
  // overwrite $data['file'] with your curlfile thingy
}
```

that way it works for both places you're looking at, as well as any future tests that wind up being necessary

**Comment by mjordan** [comment]
Sounds good!

**Comment by qadan** [comment]
... just noticed the logic I wrote _technically_ fails for PHP 7, though that supposedly will never be an issue with Drupal 7. Eh.

**Comment by mjordan** [comment]
@qadan Decided to try `version_compare()` as it seemed to be the right tool.

**Comment by qadan** [comment]
Agreed; that seems to fit Islandora convention too.

**Pull request merged**
